### ISSUE TITLE
'Unhandled Promise Rejection Warning' after running command

### ISSUE THREAD

**Issue by samwrigley** [thesold/stacklint#8]
When running any `stacklint` command, I get the following error after confirming 'Yes' to 'Are you sure you want to continue?':

`(node:84425) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: fs.copyFileSync is not a function
(node:84425) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Node: v8.1.3
NPM: v5.5.1

**Comment by m2de** [comment]
Strange. I don't get any errors. Could you try upgrading node/npm?

Node: 8.7.0+
NPM: 5.6.0+

**Comment by samwrigley** [comment]
Hi @m2de, upgrading Node to v9.4.0 fixed the issue.
